// <auto-generated />
using System;
using ControleCursos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ControleCursos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210629112031_inicial")]
    partial class inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("ControleCursos.Data.Categoria", b =>
                {
                    b.Property<int>("codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("codigo");

                    b.ToTable("categoria");
                });

            modelBuilder.Entity("ControleCursos.Data.Curso", b =>
                {
                    b.Property<int>("codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("categoriacodigo")
                        .HasColumnType("integer");

                    b.Property<DateTime>("dataInicio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("dataTermino")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("descricaoAssunto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("qtdAlunosTurma")
                        .HasColumnType("integer");

                    b.HasKey("codigo");

                    b.HasIndex("categoriacodigo");

                    b.ToTable("cursos");
                });

            modelBuilder.Entity("ControleCursos.Data.Curso", b =>
                {
                    b.HasOne("ControleCursos.Data.Categoria", "categoria")
                        .WithMany()
                        .HasForeignKey("categoriacodigo");

                    b.Navigation("categoria");
                });
#pragma warning restore 612, 618
        }
    }
}
